### ISSUE TITLE
not able to jump while in crouch position

### ISSUE THREAD

**Issue by jurassicjordan** [EricXu1728/Godot4SourceEngineMovement#8]
I am not able to jump while in crouch position, only after letting go of crouch can the player jump

**Comment by EricXu1728** [comment]
This is expected behavior. In some source games you cannot jump while crouched, but I may be mistaken. 
If you do want to jump for your project, go to Run.gd and change the line

` if Input.is_action_pressed("jump") && (not stats.crouched) && stats.shouldJump:`

to
`if Input.is_action_pressed("jump") && stats.shouldJump:`
